"""empty message

Revision ID: ab20c670cd00
Revises: fa2a248e1f79
Create Date: 2022-03-23 23:18:45.138972+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab20c670cd00"
down_revision = "fa2a248e1f79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_people_name", ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.drop_constraint("uq_people_name", type_="unique")

    # ### end Alembic commands ###
