"""remove timers, update null constraints, convert to flask-migrate

Revision ID: d56d7a0e0eed
Revises: ab20c670cd00
Create Date: 2026-01-11 04:53:55.621460+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56d7a0e0eed'
down_revision = 'ab20c670cd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timers')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('counter',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('counter',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('timers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('frequency', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
